### ISSUE TITLE
Selective branch ?

### ISSUE THREAD

**Issue by melMass** [fips-libs/fips-imgui#4]
Hi,

Since I started using the sokol headers, I'm trying to create my fipsified libs but I can't seem to find much information, specifically about the `fip_files` possibilities.
I'm working on a project on which I use the docking branch of Dear ImGui, I was wondering if there is a way to do that from fips?

Thanks

**Comment by floooh** [comment]
Yes you can specify a branch or tag name, or a commit hash in the fips.yml file, see here for details:

http://floooh.github.io/fips/docs/imports/#importing-specific-versions

I'm currently not sure if a switch is done for dependencies that already exist in the file system when doing an ```fips update```, if it doesn't then it's best to delete the dependency from the file system and do a ```fips fetch```.

However if you're using Dear ImGui via https://github.com/fips-libs/fips-imgui, this approach doesn't help much because fips-imgui doesn't have a separate branch for the Dear ImGui docking branch (but you can fork fips-imgui, and modify it to your needs, and then use the URL of your fork in the fips.yml file).

**Comment by melMass** [comment]
Thanks.
Yes, I went that second road yesterday (https://github.com/melMass/fips-imgui-dock) and it allowed me to understand fips a little more, especially the relation between CMake and Python, I like it a lot.

What would be nice is to also be able to specify the version of a submodule as a lot of fips libs are built that way, but I guess it's a lot of work...

Are you willing to create a docking branch of your fips-imgui repo ?

**Comment by floooh** [comment]
> Are you willing to create a docking branch of your fips-imgui repo ?

Yes I think that would make sense, I'll open a separate reminder issue.
